from PyQt5 import QtCore, QtGui, QtWidgets

RA = 00
RB = 00
RC = 00
RD = 00
RE = 00
RF = 00
RH = 00
RL = 00
RW = 00
RZ = 00
ARA = 00
ARB = 00
ARC = 00
ARD = 00
ARE = 00
ARF = 00
ARH = 00
ARL = 00
ARW = 00
ARZ = 00
RI = 00
RR = 00
IX = 0000
IY = 0000
SP = 0000
PC = 0000
ID_BUS = 0000
ADD_BUS = 0000
CON_BUS = 0000
M1 = 0
MREQ = 0
IORQ = 0
RD = 0
WRT = 0
RFSH = 0
HALT = 0
WAIT = 0
INT = 0
NMI = 0
RESET = 0
BUSRQ = 0
BUSRACK = 0
LAST_INS = ""
NEXT_INS = ""

class Ui_Z80Simulator(object):
    def setupUi(self, Z80Simulator):
        Z80Simulator.setObjectName("Z80Simulator")
        Z80Simulator.resize(451, 579)
        Z80Simulator.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Z80Simulator)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 91, 331))
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 20, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setSegmentStyle(2)
        self.lcdNumber.setHexMode()
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 50, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_2.setSegmentStyle(2)
        self.lcdNumber_2.setHexMode()
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(20, 80, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_3.setSegmentStyle(2)
        self.lcdNumber_3.setHexMode()
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(20, 110, 64, 23))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_4.setSegmentStyle(2)
        self.lcdNumber_4.setHexMode()
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_5.setGeometry(QtCore.QRect(20, 140, 64, 23))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_5.setSegmentStyle(2)
        self.lcdNumber_5.setHexMode()
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_6.setGeometry(QtCore.QRect(20, 170, 64, 23))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_6.setSegmentStyle(2)
        self.lcdNumber_6.setHexMode()
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 23, 16, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 16, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 16, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 16, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 16, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 16, 20))
        self.label_6.setObjectName("label_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_7.setGeometry(QtCore.QRect(20, 200, 64, 23))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_7.setSegmentStyle(2)
        self.lcdNumber_7.setHexMode()
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_8.setGeometry(QtCore.QRect(20, 230, 64, 23))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_8.setSegmentStyle(2)
        self.lcdNumber_8.setHexMode()
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_9.setGeometry(QtCore.QRect(20, 260, 64, 23))
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_9.setSegmentStyle(2)
        self.lcdNumber_9.setHexMode()
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_10.setGeometry(QtCore.QRect(20, 290, 64, 23))
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_10.setSegmentStyle(2)
        self.lcdNumber_10.setHexMode()
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 16, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 16, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 16, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 16, 20))
        self.label_10.setObjectName("label_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 30, 201, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_21.setGeometry(QtCore.QRect(30, 20, 64, 23))
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_21.setSegmentStyle(2)
        self.lcdNumber_21.setHexMode()
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_22.setGeometry(QtCore.QRect(30, 50, 64, 23))
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.lcdNumber_22.setSegmentStyle(2)
        self.lcdNumber_22.setHexMode()
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_23.setGeometry(QtCore.QRect(130, 20, 64, 23))
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.lcdNumber_23.setSegmentStyle(2)
        self.lcdNumber_23.setHexMode()
        self.lcdNumber_24 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_24.setGeometry(QtCore.QRect(130, 50, 64, 23))
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.lcdNumber_24.setSegmentStyle(2)
        self.lcdNumber_24.setHexMode()
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 16, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 16, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(110, 20, 16, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(110, 50, 16, 20))
        self.label_24.setObjectName("label_24")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 250, 201, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lcdNumber_25 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_25.setGeometry(QtCore.QRect(30, 20, 64, 23))
        self.lcdNumber_25.setObjectName("lcdNumber_25")
        self.lcdNumber_25.setSegmentStyle(2)
        self.lcdNumber_25.setHexMode()
        self.lcdNumber_26 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_26.setGeometry(QtCore.QRect(130, 20, 64, 23))
        self.lcdNumber_26.setObjectName("lcdNumber_26")
        self.lcdNumber_26.setSegmentStyle(2)
        self.lcdNumber_26.setHexMode()
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(10, 20, 16, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(110, 20, 16, 20))
        self.label_26.setObjectName("label_26")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(120, 30, 91, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_11.setGeometry(QtCore.QRect(20, 20, 64, 23))
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_11.setSegmentStyle(2)
        self.lcdNumber_11.setHexMode()
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_12.setGeometry(QtCore.QRect(20, 50, 64, 23))
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_12.setSegmentStyle(2)
        self.lcdNumber_12.setHexMode()
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_13.setGeometry(QtCore.QRect(20, 80, 64, 23))
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_13.setSegmentStyle(2)
        self.lcdNumber_13.setHexMode()
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_14.setGeometry(QtCore.QRect(20, 110, 64, 23))
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.lcdNumber_14.setSegmentStyle(2)
        self.lcdNumber_14.setHexMode()
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_15.setGeometry(QtCore.QRect(20, 140, 64, 23))
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_15.setSegmentStyle(2)
        self.lcdNumber_15.setHexMode()
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_16.setGeometry(QtCore.QRect(20, 170, 64, 23))
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.lcdNumber_16.setSegmentStyle(2)
        self.lcdNumber_16.setHexMode()
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 23, 16, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 16, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 16, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 16, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 16, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 16, 20))
        self.label_16.setObjectName("label_16")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_17.setGeometry(QtCore.QRect(20, 200, 64, 23))
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.lcdNumber_17.setSegmentStyle(2)
        self.lcdNumber_17.setHexMode()
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_18.setGeometry(QtCore.QRect(20, 230, 64, 23))
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.lcdNumber_18.setSegmentStyle(2)
        self.lcdNumber_18.setHexMode()
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_19.setGeometry(QtCore.QRect(20, 260, 64, 23))
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_19.setSegmentStyle(2)
        self.lcdNumber_19.setHexMode()
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_20.setGeometry(QtCore.QRect(20, 290, 64, 23))
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_20.setSegmentStyle(2)
        self.lcdNumber_20.setHexMode()
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 200, 16, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 230, 16, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 260, 16, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 290, 16, 20))
        self.label_20.setObjectName("label_20")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(230, 120, 201, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lcdNumber_27 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_27.setGeometry(QtCore.QRect(120, 20, 64, 23))
        self.lcdNumber_27.setObjectName("lcdNumber_27")
        self.lcdNumber_27.setSegmentStyle(2)
        self.lcdNumber_27.setHexMode()
        self.lcdNumber_27.display(ID_BUS)
        self.lcdNumber_28 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_28.setGeometry(QtCore.QRect(120, 50, 64, 23))
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.lcdNumber_28.setSegmentStyle(2)
        self.lcdNumber_28.setHexMode()
        self.lcdNumber_28.display(ADD_BUS)
        self.lcdNumber_29 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_29.setGeometry(QtCore.QRect(120, 80, 64, 23))
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.lcdNumber_29.setSegmentStyle(2)
        self.lcdNumber_29.setHexMode()
        self.lcdNumber_29.display(CON_BUS)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(20, 20, 91, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(20, 50, 71, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.label_29.setObjectName("label_29")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(280, 360, 81, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 370, 51, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 390, 51, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(230, 410, 51, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(230, 430, 51, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(230, 450, 51, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(230, 470, 51, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(360, 370, 51, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(360, 390, 51, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(360, 410, 51, 31))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(360, 430, 51, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(360, 450, 51, 31))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(360, 470, 51, 31))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(360, 490, 51, 31))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(260, 380, 20, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(250, 400, 31, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(250, 420, 31, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(260, 440, 20, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(250, 460, 31, 20))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(250, 480, 31, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(360, 380, 31, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(360, 400, 31, 20))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(360, 420, 20, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(360, 440, 20, 20))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(360, 460, 41, 20))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(360, 480, 41, 20))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(360, 500, 51, 20))
        self.label_42.setObjectName("label_42")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(220, 370, 16, 31))
        self.label_49.setObjectName("label_49")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(220, 390, 16, 31))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(220, 410, 16, 31))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(220, 430, 16, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(220, 450, 16, 31))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(220, 470, 16, 31))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(410, 370, 16, 31))
        self.label_48.setObjectName("label_48")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(410, 390, 16, 31))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(410, 410, 16, 31))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(410, 430, 16, 31))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(410, 450, 16, 31))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(410, 470, 16, 31))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(410, 490, 16, 31))
        self.label_55.setObjectName("label_55")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 410, 151, 41))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_56 = QtWidgets.QLabel(self.groupBox_7)
        self.label_56.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label_56.setObjectName("label_56")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 460, 151, 41))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_57 = QtWidgets.QLabel(self.groupBox_8)
        self.label_57.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label_57.setObjectName("label_57")
        Z80Simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Z80Simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        Z80Simulator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Z80Simulator)
        self.statusbar.setObjectName("statusbar")
        Z80Simulator.setStatusBar(self.statusbar)
        self.retranslateUi(Z80Simulator)
        QtCore.QMetaObject.connectSlotsByName(Z80Simulator)

    def refreshRegisters(self, Z80Simulator):
        self.lcdNumber.display(RA)
        self.lcdNumber_2.display(RB)
        self.lcdNumber_3.display(RC)
        self.lcdNumber_4.display(RD)
        self.lcdNumber_5.display(RE)
        self.lcdNumber_6.display(RF)
        self.lcdNumber_7.display(RH)
        self.lcdNumber_8.display(RL)
        self.lcdNumber_9.display(RW)
        self.lcdNumber_10.display(RZ)
        self.lcdNumber_11.display(ARA)
        self.lcdNumber_12.display(ARB)
        self.lcdNumber_13.display(ARC)
        self.lcdNumber_14.display(ARD)
        self.lcdNumber_15.display(ARE)
        self.lcdNumber_16.display(ARF)
        self.lcdNumber_17.display(ARH)
        self.lcdNumber_18.display(ARL)
        self.lcdNumber_19.display(ARW)
        self.lcdNumber_20.display(ARZ)
        self.lcdNumber_21.display(IX)
        self.lcdNumber_22.display(IY)
        self.lcdNumber_23.display(SP)
        self.lcdNumber_24.display(PC)
        self.lcdNumber_25.display(RI)
        self.lcdNumber_26.display(RR)

    def retranslateUi(self, Z80Simulator):
        _translate = QtCore.QCoreApplication.translate
        Z80Simulator.setWindowTitle(_translate("Z80Simulator", "MainWindow"))
        self.groupBox.setTitle(_translate("Z80Simulator", "Main Registers"))
        self.label.setText(_translate("Z80Simulator", "A"))
        self.label_2.setText(_translate("Z80Simulator", "B"))
        self.label_3.setText(_translate("Z80Simulator", "C"))
        self.label_4.setText(_translate("Z80Simulator", "D"))
        self.label_5.setText(_translate("Z80Simulator", "E"))
        self.label_6.setText(_translate("Z80Simulator", "F"))
        self.label_7.setText(_translate("Z80Simulator", "H"))
        self.label_8.setText(_translate("Z80Simulator", "L"))
        self.label_9.setText(_translate("Z80Simulator", "W"))
        self.label_10.setText(_translate("Z80Simulator", "Z"))
        self.groupBox_3.setTitle(_translate("Z80Simulator", "16-Bit Registers"))
        self.label_21.setText(_translate("Z80Simulator", "IX"))
        self.label_22.setText(_translate("Z80Simulator", "IY"))
        self.label_23.setText(_translate("Z80Simulator", "SP"))
        self.label_24.setText(_translate("Z80Simulator", "PC"))
        self.groupBox_4.setTitle(_translate("Z80Simulator", "Special Registers"))
        self.label_25.setText(_translate("Z80Simulator", "I"))
        self.label_26.setText(_translate("Z80Simulator", "R"))
        self.groupBox_2.setTitle(_translate("Z80Simulator", "Altern Registers"))
        self.label_11.setText(_translate("Z80Simulator", "A\'"))
        self.label_12.setText(_translate("Z80Simulator", "B\'"))
        self.label_13.setText(_translate("Z80Simulator", "C\'"))
        self.label_14.setText(_translate("Z80Simulator", "D\'"))
        self.label_15.setText(_translate("Z80Simulator", "E\'"))
        self.label_16.setText(_translate("Z80Simulator", "F\'"))
        self.label_17.setText(_translate("Z80Simulator", "H\'"))
        self.label_18.setText(_translate("Z80Simulator", "L\'"))
        self.label_19.setText(_translate("Z80Simulator", "W\'"))
        self.label_20.setText(_translate("Z80Simulator", "Z\'"))
        self.groupBox_5.setTitle(_translate("Z80Simulator", "Bus"))
        self.label_27.setText(_translate("Z80Simulator", "Internal Data Bus"))
        self.label_28.setText(_translate("Z80Simulator", "Address Bus"))
        self.label_29.setText(_translate("Z80Simulator", "Control Bus"))
        self.groupBox_6.setTitle(_translate("Z80Simulator", "Z-80"))
        self.label_30.setText(_translate("Z80Simulator", "M1"))
        self.label_31.setText(_translate("Z80Simulator", "MREQ"))
        self.label_32.setText(_translate("Z80Simulator", "IORQ"))
        self.label_33.setText(_translate("Z80Simulator", "RD"))
        self.label_34.setText(_translate("Z80Simulator", "WRT"))
        self.label_35.setText(_translate("Z80Simulator", "RFSH"))
        self.label_36.setText(_translate("Z80Simulator", "HALT"))
        self.label_37.setText(_translate("Z80Simulator", "WAIT"))
        self.label_38.setText(_translate("Z80Simulator", "INT"))
        self.label_39.setText(_translate("Z80Simulator", "NMI"))
        self.label_40.setText(_translate("Z80Simulator", "RESET"))
        self.label_41.setText(_translate("Z80Simulator", "BUSRQ"))
        self.label_42.setText(_translate("Z80Simulator", "BUSRACK"))
        self.label_49.setText(_translate("Z80Simulator", str(M1)))
        self.label_43.setText(_translate("Z80Simulator", str(MREQ)))
        self.label_44.setText(_translate("Z80Simulator", str(IORQ)))
        self.label_45.setText(_translate("Z80Simulator", str(RD)))
        self.label_46.setText(_translate("Z80Simulator", str(WRT)))
        self.label_47.setText(_translate("Z80Simulator", str(RFSH)))
        self.label_48.setText(_translate("Z80Simulator", str(HALT)))
        self.label_50.setText(_translate("Z80Simulator", str(WAIT)))
        self.label_51.setText(_translate("Z80Simulator", str(INT)))
        self.label_52.setText(_translate("Z80Simulator", str(NMI)))
        self.label_53.setText(_translate("Z80Simulator", str(RESET)))
        self.label_54.setText(_translate("Z80Simulator", str(BUSRQ)))
        self.label_55.setText(_translate("Z80Simulator", str(BUSRACK)))
        self.pushButton.setText(_translate("Z80Simulator", "Siguiente"))
        self.groupBox_7.setTitle(_translate("Z80Simulator", "Anterior Instrucción"))
        self.label_56.setText(_translate("Z80Simulator", LAST_INS))
        self.groupBox_8.setTitle(_translate("Z80Simulator", "Siguiente Instrucción"))
        self.label_57.setText(_translate("Z80Simulator", NEXT_INS))

if __name__ == "__main__":
    import sys
    loop = 1
    app = QtWidgets.QApplication(sys.argv)
    Z80Simulator = QtWidgets.QMainWindow()
    ui = Ui_Z80Simulator()
    ui.setupUi(Z80Simulator)
    Z80Simulator.show()
    keys = []
    keys.extend(range(0,2**16))
    memory = {}
    memory = dict.fromkeys(keys)
    file = open("assemblerCode.txt","r")
    aux = 0
    for line in file:
        words = line.split()
        for word in words:
            memory[aux] = word
            print(memory[aux])
            aux = aux+1
    #print(int("f",16))
    while(loop==1):
        #RA = int(input("INGRESE REGISTRO A:"))
        
        ui.refreshRegisters(Z80Simulator)
        ui.retranslateUi(Z80Simulator)
    sys.exit(app.exec_())
